# FIXME:
# DISABLED STORAGE FOR THE INITIAL VERSION SINCE BUILDING IS LIMITED TO A FEW SECONDS

version: "3.4"
services:
  api:
    build: "."
    container_name: goblin_api
    depends_on:
      - createbuckets
    env_file: .env
    expose:
      - "3000:3000"
    environment:
      MINIO_URL: goblin_minio:9000
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app"

  createbuckets:
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://goblin_minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb -p myminio/$$BUCKET_NAME;
      /usr/bin/mc policy set public myminio/$$BUCKET_NAME;
      exit 0;
      "
    env_file:
      - .env
    image: minio/mc

  minio:
    command: 'server --console-address ":9001" /home/files'
    container_name: goblin_minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    env_file:
      - .env
    image: "minio/minio:RELEASE.2022-01-08T03-11-54Z"
    expose:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "goblin:/home/files"

  nginx:
    container_name: goblin_nginx
    depends_on:
      # - minio
      - api
    hostname: nginx
    image: "nginx:1.19.2-alpine"
    ports:
      - "80:80"
      - "9000:9000"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"

volumes:
  goblin: ~
